import { mkdtemp, mkdir, realpath, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import {
  ProjectExecInputSchema,
  type ProjectExecInput,
  type ProjectExecOperation,
} from '@chatsplice/protocol';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { WorkspaceService } from '../workspace/service.js';
import { SqliteWorkspaceRepository } from '../workspace/sqlite-repository.js';
import { executeProjectOperation } from './pi-execution.js';

const WORKSPACE_BINDING = `wb_${'0'.repeat(64)}`;

describe('executeProjectOperation', () => {
  let temporaryDirectory: string;
  let workspaceRoot: string;
  let repository: SqliteWorkspaceRepository;
  let service: WorkspaceService;
  let workspaceId: string;

  function supportedRuntime(): boolean {
    const [majorText, minorText] = process.versions.node.split('.');
    const major = Number(majorText);
    const minor = Number(minorText);
    return major > 22 || (major === 22 && minor >= 19);
  }

  const itOnSupportedMac = it.skipIf(process.platform !== 'darwin' || !supportedRuntime());

  beforeEach(async () => {
    temporaryDirectory = await mkdtemp(join(tmpdir(), 'chatsplice-core-pi-execution-'));
    workspaceRoot = join(temporaryDirectory, 'workspace');
    await mkdir(workspaceRoot);
    await writeFile(
      join(workspaceRoot, 'package.json'),
      JSON.stringify({
        name: 'pi-execution-fixture',
        version: '1.0.0',
        private: true,
        packageManager: 'npm@10.0.0',
        scripts: {
          check:
            "node -e \"process.stdout.write(process.env.OPENAI_API_KEY || 'clean');try{process.stdout.write(require('node:fs').readFileSync('.env','utf8'))}catch{process.stdout.write(':secret-blocked')}\"",
          nested: 'npm run check',
          external:
            "node -e \"const net=require('node:net');const socket=net.createConnection({host:'198.51.100.1',port:80});socket.on('connect',()=>process.exit(5));socket.on('error',(error)=>process.exit(error.code==='EACCES'||error.code==='EPERM'?0:6));setTimeout(()=>process.exit(4),1000)\"",
          wait: 'node -e "setInterval(() => {}, 1000)"',
          server:
            "node -e \"const http=require('node:http');const server=http.createServer((_request,response)=>response.end('ok'));server.listen(0,'127.0.0.1',()=>{const address=server.address();if(typeof address !== 'object' || address === null) process.exit(2);http.get('http://127.0.0.1:'+address.port,(response)=>{response.resume();response.on('end',()=>process.stdout.write('ready'))})});setInterval(()=>{},1000)\"",
          output: 'node -e "process.stdout.write(\'x\'.repeat(70000))"',
        },
      }),
      'utf8',
    );
    await writeFile(
      join(workspaceRoot, 'package-lock.json'),
      JSON.stringify({
        name: 'pi-execution-fixture',
        version: '1.0.0',
        lockfileVersion: 3,
        requires: true,
        packages: { '': { name: 'pi-execution-fixture', version: '1.0.0' } },
      }),
      'utf8',
    );
    await writeFile(join(workspaceRoot, '.env'), 'SECRET_FROM_ENV_FILE\n', 'utf8');
    await mkdir(join(workspaceRoot, 'rust'));
    await writeFile(
      join(workspaceRoot, 'rust', 'Cargo.toml'),
      '[package]\nname = "pi_fixture"\nversion = "0.1.0"\nedition = "2021"\n',
      'utf8',
    );
    await writeFile(
      join(workspaceRoot, 'rust', 'Cargo.lock'),
      '# This file is automatically @generated by Cargo.\nversion = 3\n\n[[package]]\nname = "pi_fixture"\nversion = "0.1.0"\n',
      'utf8',
    );
    await mkdir(join(workspaceRoot, 'rust', 'src'));
    await writeFile(join(workspaceRoot, 'rust', 'src', 'main.rs'), 'fn main() {}\n', 'utf8');
    repository = new SqliteWorkspaceRepository(join(temporaryDirectory, 'state.sqlite'));
    service = new WorkspaceService(repository);
    workspaceId = (await service.register({ root_path: workspaceRoot })).workspace_id;
  });

  afterEach(async () => {
    repository.close();
    await rm(temporaryDirectory, { recursive: true, force: true });
  });

  function input(
    operation: ProjectExecOperation,
    extra: { cwd?: string; timeout_ms?: number } = {},
  ) {
    return ProjectExecInputSchema.parse({
      workspace_id: workspaceId,
      workspace_binding: WORKSPACE_BINDING,
      request_id: 'pi-test-1234',
      operation,
      timeout_ms: 20_000,
      ...extra,
    });
  }

  itOnSupportedMac(
    'runs an existing Node script through the Pi SDK without model/auth state',
    async () => {
      const output: string[] = [];
      const starts: unknown[] = [];
      const previous = process.env.OPENAI_API_KEY;
      process.env.OPENAI_API_KEY = 'must-not-leak';
      try {
        const result = await executeProjectOperation(
          service,
          input({ kind: 'node_script', script: 'check' }),
          {
            onOutput: (data) => output.push(data),
            onStart: (start) => starts.push(start),
          },
        );
        expect(result).toMatchObject({ exit_code: 0, timed_out: false });
        expect(starts).toEqual([{ command: 'npm run check', used_network: false }]);
        expect(output.join('')).toContain('clean');
        expect(output.join('')).toContain(':secret-blocked');
        expect(output.join('')).not.toContain('must-not-leak');
        expect(output.join('')).not.toContain('SECRET_FROM_ENV_FILE');
      } finally {
        if (previous === undefined) delete process.env.OPENAI_API_KEY;
        else process.env.OPENAI_API_KEY = previous;
      }
    },
  );

  itOnSupportedMac('runs locked dependency install with network marked explicitly', async () => {
    const starts: unknown[] = [];
    const result = await executeProjectOperation(
      service,
      input({ kind: 'install', ecosystem: 'node' }),
      { onStart: (start) => starts.push(start) },
    );
    expect(result).toMatchObject({ exit_code: 0, timed_out: false });
    expect(starts).toEqual([{ command: 'npm ci --ignore-scripts', used_network: true }]);
  });

  itOnSupportedMac('resolves a Node lockfile without installing dependencies', async () => {
    const starts: unknown[] = [];
    const result = await executeProjectOperation(
      service,
      input({ kind: 'install', ecosystem: 'node', mode: 'resolve' }),
      { onStart: (start) => starts.push(start) },
    );
    expect(result).toMatchObject({ exit_code: 0, timed_out: false });
    expect(starts).toEqual([
      { command: 'npm install --package-lock-only --ignore-scripts', used_network: true },
    ]);
  });

  itOnSupportedMac('keeps nested package-manager calls on the trusted private shim', async () => {
    const output: string[] = [];
    const result = await executeProjectOperation(
      service,
      input({ kind: 'node_script', script: 'nested' }),
      { onOutput: (data) => output.push(data) },
    );
    expect(result).toMatchObject({ exit_code: 0, timed_out: false });
    expect(output.join('')).toContain('clean');
    expect(output.join('')).toContain(':secret-blocked');
  });

  itOnSupportedMac('denies external network access for Node scripts', async () => {
    const result = await executeProjectOperation(
      service,
      input({ kind: 'node_script', script: 'external' }),
    );
    expect(result).toMatchObject({ exit_code: 0, timed_out: false });
  });

  itOnSupportedMac('rejects pnpm-managed runtime downloads before spawning', async () => {
    await writeFile(
      join(workspaceRoot, 'package.json'),
      JSON.stringify({
        name: 'pi-execution-fixture',
        version: '1.0.0',
        private: true,
        packageManager: 'pnpm@10.33.2',
      }),
      'utf8',
    );
    await writeFile(join(workspaceRoot, 'pnpm-lock.yaml'), 'lockfileVersion: 9.0\n', 'utf8');
    await writeFile(join(workspaceRoot, 'pnpm-workspace.yaml'), 'useNodeVersion: 20.0.0\n', 'utf8');
    await expect(
      executeProjectOperation(service, input({ kind: 'install', ecosystem: 'node' })),
    ).rejects.toMatchObject({ code: 'BAD_REQUEST' });
  });

  itOnSupportedMac('rejects workspace Cargo configuration before spawning', async () => {
    await mkdir(join(workspaceRoot, '.cargo'));
    await writeFile(
      join(workspaceRoot, '.cargo', 'config.toml'),
      '[net]\noffline = false\n',
      'utf8',
    );
    await expect(
      executeProjectOperation(service, input({ kind: 'cargo', task: 'check' }, { cwd: 'rust' })),
    ).rejects.toMatchObject({ code: 'BAD_REQUEST' });
  });

  itOnSupportedMac(
    'runs a dependency-free Rust check offline with the real toolchain',
    async () => {
      const result = await executeProjectOperation(
        service,
        input({ kind: 'cargo', task: 'check' }, { cwd: 'rust' }),
      );
      expect(result).toMatchObject({ exit_code: 0, timed_out: false });
    },
  );

  itOnSupportedMac(
    'returns an exact cancellation result and cleans the process group',
    async () => {
      const controller = new AbortController();
      const execution = executeProjectOperation(
        service,
        input({ kind: 'node_script', script: 'wait' }, { timeout_ms: 20_000 }),
        { signal: controller.signal },
      );
      setTimeout(() => controller.abort(), 200).unref();
      await expect(execution).resolves.toMatchObject({ exit_code: null, timed_out: false });
    },
  );

  itOnSupportedMac('allows a Node script to bind and connect to loopback only', async () => {
    const controller = new AbortController();
    let ready = false;
    const execution = executeProjectOperation(
      service,
      input({ kind: 'node_script', script: 'server' }, { timeout_ms: 20_000 }),
      {
        signal: controller.signal,
        onOutput: (data) => {
          if (data.includes('ready')) {
            ready = true;
            controller.abort();
          }
        },
      },
    );
    setTimeout(() => controller.abort(), 1_000).unref();
    await expect(execution).resolves.toMatchObject({ exit_code: null, timed_out: false });
    expect(ready).toBe(true);
  });

  itOnSupportedMac('rejects executable roots that would expose the workspace parent', async () => {
    const bin = join(temporaryDirectory, 'bin');
    await mkdir(bin);
    await writeFile(join(bin, 'pnpm'), '#!/bin/sh\nexit 0\n', { mode: 0o700 });
    await writeFile(
      join(workspaceRoot, 'package.json'),
      JSON.stringify({ packageManager: 'pnpm@10.33.2', scripts: { check: 'node check.js' } }),
    );
    const previousPath = process.env.PATH;
    try {
      process.env.PATH = await realpath(bin);
      await expect(
        executeProjectOperation(service, input({ kind: 'node_script', script: 'check' })),
      ).rejects.toThrow('A trusted pnpm executable was not found');
    } finally {
      if (previousPath === undefined) delete process.env.PATH;
      else process.env.PATH = previousPath;
    }
  });

  itOnSupportedMac(
    'rejects cwd traversal and symlink escape before starting the SDK tool',
    async () => {
      const traversalInput = {
        ...input({ kind: 'node_script', script: 'check' }),
        cwd: '../',
      } as ProjectExecInput;
      await expect(executeProjectOperation(service, traversalInput)).rejects.toMatchObject({
        code: 'PATH_OUTSIDE_WORKSPACE',
      });

      const outside = join(temporaryDirectory, 'outside');
      await mkdir(outside);
      await symlink(outside, join(workspaceRoot, 'linked'));
      await expect(
        executeProjectOperation(
          service,
          input({ kind: 'node_script', script: 'check' }, { cwd: 'linked' }),
        ),
      ).rejects.toMatchObject({ code: 'PATH_OUTSIDE_WORKSPACE' });
    },
  );

  itOnSupportedMac(
    'keeps the SDK input below its raw-output spool threshold while streaming full job output',
    async () => {
      const output: string[] = [];
      const result = await executeProjectOperation(
        service,
        input({ kind: 'node_script', script: 'output' }),
        { onOutput: (data) => output.push(data) },
      );
      expect(result.exit_code).toBe(0);
      expect(Buffer.byteLength(output.join(''), 'utf8')).toBeGreaterThanOrEqual(70_000);
    },
  );
});
